[package]
name = "pepeeltoro41/replecs"
version = "0.1.0-alpha1"
description = "Networking library for Jecs"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = [
    "default.project.json",
    "src",
    "src/**",
    "wally.toml",
    ".luaurc",
    "README.md",
    "LICENSE",
]
exclude = ["**"]

[dependencies]
jecs = "ukendio/jecs@0.8.3"
